### ISSUE TITLE
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.184.134}{192.168.184.134:9300}]]

### ISSUE THREAD

**Issue by gaoxinfu** [gaoxinfu/demo-elk#2]
五月 12, 2018 1:22:11 下午 org.elasticsearch.plugins.PluginsService <init>
信息: [Stinger] modules [], plugins [], sites []
五月 12, 2018 1:22:12 下午 org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
信息: [Stinger] failed to get node info for {#transport#-1}{192.168.184.134}{192.168.184.134:9300}, disconnecting...
NodeDisconnectedException[[][192.168.184.134:9300][cluster:monitor/nodes/liveness] disconnected]

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.184.134}{192.168.184.134:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:286)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
	at node.IndexTest.indexCreate(IndexTest.java:48)
	at node.IndexTest.main(IndexTest.java:27)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0

**Comment by gaoxinfu** [comment]
这个一般是java客户端的elasticsearch版本与服务端的elasticsearch版本不一致导致
